package com.atguigu.mybatis.mapper;

import com.atguigu.mybatis.pojo.Dept;
import java.util.List;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Sat Dec 07 17:10:43 CST 2024
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Sat Dec 07 17:10:43 CST 2024
     */
    List<Dept> selectAll();
}